services:
# Database
  review-db-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/cqrs-postgres:/var/lib/postgresql
      - ~/Desktop/tmp:/tmp
    ports:
      - '10001:5432'
  
  product-db-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/cqrs-postgres:/var/lib/postgresql
      - ~/Desktop/tmp:/tmp
    ports:
      - '10002:5432'
  
  offert-db-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/cqrs-postgres:/var/lib/postgresql
      - ~/Desktop/tmp:/tmp
    ports:
      - '10003:5432'
  
  user-db-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/cqrs-postgres:/var/lib/postgresql
      - ~/Desktop/tmp:/tmp
    ports:
      - '10004:5432'

# Discovery Server
  smart-consumption-register-ms:
    build: ./smart-consumption-register-ms
    ports:
      - "8761:8761"
    container_name: smart-consumption-register-ms

# API Gateway
  smart-consumption-api-gateway:
    build: ./smart-consumption-api-gateway
    ports:
      - "8080:8080"
    container_name: smart-consumption-api-gateway
    environment:
      - KEYCLOAK_URL=http://keycloak.local:9090

# RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
  
# Review Microservice
  smart-consumption-review-ms:
    build: ./smart-consumption-review-ms   
    depends_on:
      - review-db-postgres
      - smart-consumption-register-ms
      - smart-consumption-api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://review-db-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

# Product Microservice
  smart-consumption-product-ms:
    build: ./smart-consumption-product-ms
    depends_on:
      - product-db-postgres
      - smart-consumption-register-ms
      - smart-consumption-api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

# Offert Microservice
  smart-consumption-offert-ms:
    build: ./smart-consumption-offert-ms
    depends_on:
      - offert-db-postgres
      - smart-consumption-register-ms
      - smart-consumption-api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://offert-db-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

# User Microservice
  smart-consumption-user-ms:
    build: ./smart-consumption-user-ms
    depends_on:
      - user-db-postgres
      - smart-consumption-register-ms
      - smart-consumption-api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: keycloak_db_user_password

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    environment:
      KC_HOSTNAME: keycloak.local
      KC_HOSTNAME_PORT: 9090
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: keycloak_db_user
      KC_DB_PASSWORD: keycloak_db_user_password
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 9090:8080
    restart: always
    depends_on:
      - postgres
    container_name: keycloak

volumes:
  postgres_data:
    driver: local
